# .ioc and the supported build both use STM32CubeF1 v1.8.6.
set(BIONIC_FISH_CUBE_VERSION "1.8.6")
if(NOT EXISTS "${STM32CUBE_F1_PATH}/package.xml")
    message(FATAL_ERROR "STM32CUBE_F1_PATH must point to a complete STM32CubeF1 v1.8.6 package (package.xml missing).")
endif()
file(READ "${STM32CUBE_F1_PATH}/package.xml" CUBE_PACKAGE_XML)
if(NOT CUBE_PACKAGE_XML MATCHES "(Patch|Release)=\"FW\\.F1\\.1\\.8\\.6\"")
    message(FATAL_ERROR "Expected STM32CubeF1 v1.8.6; do not mix CubeMX and build dependency versions.")
endif()
message(STATUS "STM32CubeF1: ${BIONIC_FISH_CUBE_VERSION} (${STM32CUBE_F1_PATH})")
